# Generated by Django 5.2 on 2025-12-09 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_editor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InteractiveImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Optional name for this image', max_length=200)),
                ('image', models.ImageField(upload_to='interactive_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InteractiveRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_id', models.CharField(help_text="Unique identifier (e.g., 'watch', 'suit', 'boots')", max_length=100)),
                ('label', models.CharField(help_text="Display name (e.g., 'Watch', 'Suit')", max_length=200)),
                ('x_percent', models.DecimalField(decimal_places=4, help_text='X coordinate as percentage (0.0 to 1.0)', max_digits=6)),
                ('y_percent', models.DecimalField(decimal_places=4, help_text='Y coordinate as percentage (0.0 to 1.0)', max_digits=6)),
                ('width_percent', models.DecimalField(blank=True, decimal_places=4, help_text='Width as percentage (optional, for region size)', max_digits=6, null=True)),
                ('height_percent', models.DecimalField(blank=True, decimal_places=4, help_text='Height as percentage (optional, for region size)', max_digits=6, null=True)),
                ('color', models.CharField(default='#3B82F6', help_text='Hex color code for the highlight (e.g., #3B82F6)', max_length=7)),
                ('icon', models.CharField(blank=True, help_text='SF Symbol name or icon identifier (optional)', max_length=50)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('interactive_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='image_editor.interactiveimage')),
            ],
            options={
                'ordering': ['order', 'region_id'],
                'unique_together': {('interactive_image', 'region_id')},
            },
        ),
    ]
