# Generated by Django 5.2 on 2025-12-09 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_alter_customer_token_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='token_version',
            field=models.IntegerField(blank=True, db_column='token_version', default=0, help_text='Increment this to invalidate all existing JWT tokens immediately', null=True),
        ),
    ]
